version: '3.4'

services:
  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  stock.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

