version: '3.4'

services:
  order.api:
    image: orderapi:dev
    container_name: Order.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Order.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_order.api$
    volumes:
      - C:\Users\Agartha Teknoloji\source\repos\SagaExample\Order.API:/app
      - C:\Users\Agartha Teknoloji\source\repos\SagaExample:/src
      - C:\Users\Agartha Teknoloji\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_order.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_order.api$ \"/app/bin/Debug/net5.0/Order.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  payment.api:
    image: paymentapi:dev
    container_name: Payment.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Payment.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_payment.api$
    volumes:
      - C:\Users\Agartha Teknoloji\source\repos\SagaExample\Payment.API:/app
      - C:\Users\Agartha Teknoloji\source\repos\SagaExample:/src
      - C:\Users\Agartha Teknoloji\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_payment.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_payment.api$ \"/app/bin/Debug/net5.0/Payment.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  stock.api:
    image: stockapi:dev
    container_name: Stock.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Stock.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_stock.api$
    volumes:
      - C:\Users\Agartha Teknoloji\source\repos\SagaExample\Stock.API:/app
      - C:\Users\Agartha Teknoloji\source\repos\SagaExample:/src
      - C:\Users\Agartha Teknoloji\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_stock.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_stock.api$ \"/app/bin/Debug/net5.0/Stock.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
